# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['combined_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('lang', 'lang'),
        ('assets', 'assets'),
        ('launcher.ico', '.'),
        ('rounded_button.png', '.'),
        ('config.json', '.'),
        ('CHANGELOG.md', '.'),
    ],
    hiddenimports=[
        'mods',
        'servers',
        'jvm_presets',
        'updater',
        'backup',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'minecraft_launcher_lib',
        'minecraft_launcher_lib.account',
        'minecraft_launcher_lib.command',
        'minecraft_launcher_lib.install',
        'minecraft_launcher_lib.launch',
        'minecraft_launcher_lib.utils',
        'minecraft_launcher_lib.types',
        'minecraft_launcher_lib.exceptions',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.exceptions',
        'psutil',
        'psutil._psutil_windows',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        'json',
        'os',
        'sys',
        'pathlib',
        'pathlib.Path',
        'shutil',
        'threading',
        'subprocess',
        'zipfile',
        'datetime',
        'webbrowser',
        'urllib',
        'urllib.request',
        'urllib.parse',
        'ssl',
        'socket',
        'platform',
        'time',
        'uuid',
        'io',
        'traceback',
        'logging',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter.test',
        'test',
        'unittest',
        'pdb',
        'pydoc',
    ],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='OmniLauncher',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='launcher.ico',
    version_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='OmniLauncher'
)
